[tool.poetry]
name = "semantic-workbench-assistant"
version = "0.1.0"
description = "Library for facilitating the implementation of FastAPI-based Semantic Workbench assistants."
authors = ["Semantic Workbench Team"]
readme = "README.md"
packages = [{ include = "semantic_workbench_assistant" }]

[tool.poetry.dependencies]
python = "~3.11"
asgi-correlation-id = "^4.3.1"
backoff = "^2.2.1"
fastapi = { version = "~0.115.0", extras = ["standard"] }
pydantic-settings = "^2.2.0"
python-json-logger = "^2.0.7"
rich = "^13.7.0"
semantic-workbench-api-model = { path = "../semantic-workbench-api-model", develop = true }
deepmerge = "^2.0"

[tool.poetry.group.dev.dependencies]
asgi-lifespan = "^2.1.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.23.5.post1"
pytest-httpx = "^0.30.0"
ruff = "^0.6.4"

[tool.poetry.scripts]
start-semantic-workbench-assistant = "semantic_workbench_assistant.start:main"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["venv", ".venv"]

[tool.pytest.ini_options]
addopts = "-vv"
log_cli = true
log_cli_level = "WARNING"
log_cli_format = "%(asctime)s | %(levelname)-7s | %(name)s | %(message)s"
testpaths = [
    "tests"
]
asyncio_mode="auto"
