- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
	displayName: 'Run PoliCheck'
	inputs:
		targetType: F
		optionsPE: '1|2|3|4'
		optionsUEPATH: '$(Build.SourcesDirectory)\.github\policheck-exclusions.xml'
		optionsRulesDBPath: '$(Build.SourcesDirectory)\.github\policheck-exclusions.mdb'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
  displayName: 'Policheck Break Build'
	inputs:
		GdnBreakAllTools: false
		GdnBreakGdnToolPoliCheck: true
		GdnBreakGdnToolPoliCheckSeverity: Warning
