[tool.poetry]
name = "semantic-workbench-api-model"
version = "0.1.0"
description = "Library of pydantic models for requests and responses to the semantic-workbench-service and semant-workbench-assistant services."
authors = ["Semantic Workbench Team"]
readme = "README.md"
packages= [
    { include = "semantic_workbench_api_model" },
]

[tool.poetry.dependencies]
python = "~3.11"
asgi-correlation-id = "^4.3.1"
fastapi = "~0.110.0"
httpx = "~0.27.0"
pydantic = "^2.7.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["venv", ".venv"]
