[project]
name = "form-filler-skill"
version = "0.1.0"
description = "MADE:Exploration Form-filler skill"
authors = [{name="MADE:Explorers"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "skill-library>=0.1.0",
    "context>=0.1.0",
    "events>=0.1.0",
    "openai-client>=0.1.0",
    # "guided-conversation>=0.1.0",
]

[tool.uv]
package = true

[tool.uv.sources]
skill-library = { path = "../../skill-library", editable= true }
context = { path = "../../../context", editable = true }
events = { path = "../../../events", editable = true }
openai-client = { path = "../../../openai-client", editable = true }
# guided-conversation = { path = "../../../guided-conversation", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
