[tool.poetry]
name = "semantic-workbench-assistant"
version = "0.1.0"
description = "Library for facilitating the implementation of FastAPI-based Semantic Workbench assistants."
authors = ["Semantic Workbench Team"]
readme = "README.md"
packages= [
    { include = "semantic_workbench_assistant" },
]

[tool.poetry.dependencies]
python = "~3.11"
asgi-correlation-id = "^4.3.1"
# anyio is pinned to 4.3.0 because of a change in 4.4.0 (Emit a ResourceWarning for MemoryObjectReceiveStream and MemoryObjectSendStream that were garbage collected without being closed (PR by Andrey Kazantcev))
# that causes a warning in the tests. hopefully this will be fixed in the next version starlette TestClient.
anyio = "4.3.0"
backoff = "^2.2.1"
fastapi = "~0.110.0"
httpx = "~0.27.0"
pydantic-settings = "~2.3.3"
python-json-logger = "^2.0.7"
python-multipart = "~0.0.6"
rich = "^13.7.0"
semantic-workbench-api-model = { path = "../semantic-workbench-api-model", develop = true }
uvicorn = { version = "*", extras = ["standard"] }

black = { version = "^24.3.0", optional = true }
flake8 = { version = "^6.1.0", optional = true }
pytest = { version = "^7.4.3", optional = true }
pytest-asyncio = {version = "^0.23.5.post1", optional = true}
pytest-httpx = { version = "^0.30.0", optional = true }
deepmerge = "^2.0"

[tool.poetry.extras]
dev = ["black", "flake8", "pytest", "pytest-asyncio", "pytest-httpx"]

[tool.poetry.scripts]
start-semantic-workbench-assistant = "semantic_workbench_assistant.start:main"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
profile = "black"

[tool.pyright]
exclude = ["venv", ".venv"]
