[project]
name = "openai-client"
version = "0.1.0"
description = "OpenAI client for Semantic Workbench Assistants"
authors = [{ name = "Semantic Workbench Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "assistant-extensions[attachments]>=0.1.0",
    "azure-ai-contentsafety>=1.0.0",
    "azure-core[aio]>=1.30.0",
    "azure-identity>=1.17.1",
    "events>=0.1.0",
    "openai>=1.61.0",
    "pillow>=11.0.0",
    "python-liquid>=1.12.1",
    "semantic-workbench-assistant>=0.1.0",
    "tiktoken>=0.8.0",
]

[dependency-groups]
dev = ["pyright>=1.1.389", "pytest>=8.3.3"]

[tool.uv.sources]
assistant-extensions = { path = "../assistant-extensions", editable = true }
semantic-workbench-assistant = { path = "../semantic-workbench-assistant", editable = true }
events = { path = "../events", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = ["-vv"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s | %(levelname)-7s | %(name)s | %(message)s"
testpaths = ["tests"]
