[project]
name = "assistant-drive"
version = "0.1.0"
description = "MADE:Exploration Assistant Drive"
authors = [{ name = "Semantic Workbench Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "context>=0.1.0",
    "pydantic>=2.6.1",
    "pydantic-settings>=2.5.2",
    # "python-magic>=0.4.27",
    # "python-magic-bin>=0.4.14",
]

[tool.uv]
package = true
dev-dependencies = [
    "pytest>=8.3.1",
    "pytest-asyncio>=0.23.8",
    "pytest-repeat>=0.9.3",
    "ruff>=0.6.4",
    "ipykernel>=6.29.5",
]

[tool.uv.sources]
context = { path = "../../python/context", editable = true }
# python-magic = { git = "https://github.com/julian-r/python-magic.git#egg=python-magic" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
