[project]
name = "context"
version = "0.1.0"
description = "MADE:Exploration Context"
authors = [{name="MADE:Explorers"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "events>=0.1.0",
]

[tool.uv]
package = true
dev-dependencies = [
    "pytest>=8.3.1",
    "pytest-asyncio>=0.23.8",
    "pytest-repeat>=0.9.3",
]

[tool.uv.sources]
events = { path = "../events", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
exclude = [".venv"]
