[project]
name = "your-skill"
version = "0.1.0"
description = "MADE:Exploration skill"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "context>=0.1.0",
    "events>=0.1.0",
    "openai-client>=0.1.0",
    "skill-library>=0.1.0",
]

[tool.uv]
package = true

[tool.uv.sources]
context = { path = "../../../context", editable = true }
events = { path = "../../../events", editable = true }
skill-library = { path = "../../skill-library", editable = true }


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pyright>=1.1.389",
]
