ARG python_image=python:3.11-slim

FROM ${python_image} AS build

RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN pip3 install --no-cache-dir --upgrade pip

COPY ./semantic-workbench-api-model /packages/semantic-workbench-api-model
COPY ./semantic-workbench-service /packages/semantic-workbench-service

RUN pip3 install --no-cache-dir /packages/semantic-workbench-service[azure]

FROM ${python_image}

# to enable ssh in azure web app
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssh-server \
    procps \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && echo "root:Docker!" | chpasswd

COPY --from=build /venv /venv
ENV PATH=/venv/bin:$PATH

# alembic migrations related files
COPY ./semantic-workbench-service/alembic.ini ./semantic-workbench-service/alembic.ini
COPY ./semantic-workbench-service/migrations ./semantic-workbench-service/migrations

# sshd config for azure
COPY ./semantic-workbench-service/scripts/azure_website_sshd.conf /etc/ssh/sshd_config

# entrypoint script
COPY ./semantic-workbench-service/scripts/docker-entrypoint.sh ./semantic-workbench-service/scripts/docker-entrypoint.sh
RUN chmod +x ./semantic-workbench-service/scripts/docker-entrypoint.sh

WORKDIR ./semantic-workbench-service

# default to 8000
ENV port 8000

# semantic-workbench-service on ${port}, sshd on 2222
EXPOSE ${port} 2222

ENTRYPOINT ./scripts/docker-entrypoint.sh
