repo_root = $(shell git rev-parse --show-toplevel)

# Override to include all dependency groups (including examples)
UV_SYNC_INSTALL_ARGS = --all-extras --all-groups --frozen

include $(repo_root)/tools/makefiles/python.mk
