[tool.poetry]
name = "openai-content-safety-evaluator"
version = "0.1.0"
description = "OpenAI Content Safety Evaluator for Semantic Workbench Assistants"
authors = ["Semantic Workbench Team"]
readme = "README.md"
packages = [{ include = "openai_content_safety_evaluator" }]

[tool.poetry.dependencies]
python = "~3.11"
openai = "^1.3.9"

# If you copy this file to your project, you should verify the relative path to the following:
semantic-workbench-assistant = { path = "../../../semantic-workbench/v1/service/semantic-workbench-assistant", develop = true }

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["venv", ".venv"]
