[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "assistant-extensions"
version = "0.1.0"
description = "Add your description here"
authors = [{ name = "Semantic Workbench Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "assistant-drive>=0.1.0",
    "docx2txt>=0.8",
    "openai>=1.51.2",
    "pdfplumber>=0.11.4",
    "semantic-workbench-assistant>=0.1.0",
]

[project.optional-dependencies]
attachments = ["docx2txt>=0.8", "pdfplumber>=0.11.2"]

[tool.uv]
package = true

[tool.uv.sources]
semantic-workbench-assistant = { path = "../semantic-workbench-assistant", editable = true }
assistant-drive = { path = "../assistant-drive", editable = true }
