[project]
name = "anthropic-client"
version = "0.1.0"
description = "Anthropic client for Semantic Workbench Assistants"
authors = [{ name = "Semantic Workbench Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.40.0",
    "llm-client>=0.1.0",
    "events>=0.1.0",
    "pillow>=11.0.0",
    "python-liquid>=1.12.1",
    "semantic-workbench-assistant>=0.1.0",
]

[dependency-groups]
dev = ["pyright>=1.1.389"]

[tool.uv.sources]
llm-client = { path = "../llm-client", editable = true }
semantic-workbench-assistant = { path = "../semantic-workbench-assistant", editable = true }
events = { path = "../events", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = ["-vv"]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s | %(levelname)-7s | %(name)s | %(message)s"
