[tool.poetry]
name = "function-registry"
version = "0.1.0"
description = "MADE:Exploration Function Registry"
authors = ["MADE:Explorers"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
openai = "^1.16.1"
pydantic = "^2.6.1"
pydantic-settings = "^2.3.4"
python-dotenv = "^1.0.1"
requests = "^2.32.0"
tiktoken = "^0.7.0"
azure-identity = "^1.17.1"
context = { path = "../../libraries/context", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.1"
pytest-asyncio = "^0.23.8"
pytest-repeat = "^0.9.3"
ruff = "^0.6.4"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["venv", ".venv"]
