[tool.black]
line-length = 120
target-version = ["py310", "py311"]
extend-exclude = '''
(
  .git
  | __pycache__
  | build
  | dist
  | venv
  | .venv
  | .env
  | \*.egg
  | \*.egg-info
  | data
)
'''
preview = true
unstable = true
