[project]
name = "skill-notebooks"
version = "0.1.0"
authors = [{name="Paul Payne", email="<papayne@microsoft.com>"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "assistant-drive>=0.1.0",
    "azure-identity>=1.17.1",
    "chat-driver>=0.1.0",
    "context>=0.1.0",
    "events>=0.1.0",
    "function-registry>=0.1.0",
    "nest-asyncio>=1.6.0",
    "openai>=1.16.1",
    "openai-client>=0.1.0",
    "posix-skill>=0.1.0",
    "python-dotenv>=1.0.1",
    "skill-library>=0.1.0",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.4",
]

[tool.uv.sources]
assistant-drive = { path = "../../assistant-drive", editable = true }
chat-driver = { path = "../../chat-driver", editable = true }
context = { path = "../../context", editable = true }
events = { path = "../../events", editable = true }
function-registry = { path = "../../function-registry", editable = true }
posix-skill = { path = "../skills/posix-skill", editable = true }
skill-library = { path = "../skill-library/", editable = true }
openai-client = { path = "../../openai-client", editable = true }
