[tool.poetry]
name = "assistant"
version = "0.1.0"
description = "Exploration of a python Semantic Workbench OpenAI assistant to help mine artifacts for ideas."
authors = ["Semantic Workbench Team"]
readme = "README.md"
packages = [{ include = "assistant" }]

[tool.poetry.dependencies]
python = "~3.11"
deepmerge = "^2.0"
docx2txt = "^0.8"
html2docx = "^1.6.0"
markdown = "^3.6"
openai = "^1.3.9"
pdfplumber = "^0.11.2"
tiktoken = "^0.7.0"

# If you copy this file to your project, you should verify the relative path to the following:
semantic-workbench-assistant = { path = "../../libraries/python/semantic-workbench-assistant", develop = true }
content-safety = { path = "../../libraries/python/content-safety/", develop = true }

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.4"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
exclude = ["venv", ".venv"]
