[project]
name = "assistant"
version = "0.1.0"
description = "Exploration of a python Semantic Workbench OpenAI assistant to help mine artifacts for ideas."
authors = [{ name = "Semantic Workbench Team" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepmerge>=2.0",
    "docx2txt>=0.8",
    "html2docx>=1.6.0",
    "markdown>=3.6",
    "openai>=1.3.9",
    "pdfplumber>=0.11.2",
    "tiktoken>=0.7.0",
    "semantic-workbench-assistant>=0.1.0",
    "content-safety>=0.1.0",
    "chat-driver>=0.1.0",
    "skill-library>=0.1.0",
    "posix-skill>=0.1.0",
    "prospector-skill>=0.1.0",
    "document-skill>=0.1.0",
    "guided-conversation>=0.1.0",
    "openai-client>=0.1.0",
]

[tool.uv]
package = true

[tool.uv.sources]
semantic-workbench-assistant = { path = "../../libraries/python/semantic-workbench-assistant", editable = true }
content-safety = { path = "../../libraries/python/content-safety/", editable = true }
guided-conversation = { path = "../../libraries/python/guided-conversation", editable = true }
chat-driver = { path = "../../libraries/python/chat-driver", editable = true }
skill-library = { path = "../../libraries/python/skills/skill-library", editable = true }
posix-skill = { path = "../../libraries/python/skills/skills/posix-skill", editable = true }
prospector-skill = { path = "../../libraries/python/skills/skills/prospector-skill", editable = true }
document-skill = { path = "../../libraries/python/skills/skills/document-skill", editable = true }
openai-client = { path = "../../libraries/python/openai-client", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
