name: semantic-workbench-assistant tests

on:
  pull_request:
    branches: ["main"]
    paths:
      [
        "libraries/python/semantic-workbench-assistant/**",
        ".github/workflows/semantic-workbench-assistant.yml",
      ]

  push:
    branches: ["main"]
    paths:
      [
        "libraries/python/semantic-workbench-assistant/**",
        ".github/workflows/semantic-workbench-assistant.yml",
      ]

  workflow_dispatch:

defaults:
  run:
    working-directory: libraries/python/semantic-workbench-assistant

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install package
        run: uv sync

      - name: pytest
        run: uv run pytest
